site_name: ListLib Documentation
theme:
  name: material
  logo: ListLib_Icon.png
  favicon: ListLib_Favicon.png
  font:
    code: Roboto Mono
  palette:
    scheme: slate
    primary: cyan
    accent: cyan
  features:
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
nav:
  - Home: "index.md"
  - DataTypes: "dtypes.md"
  - Importing: "import.md"
  - API:
    - List: "list.md" 
    - NumList: "numlist.md"
