site_name: ListLib Documentation
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
  palette:
    scheme: slate
    primary: cyan
    accent: cyan
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list