site_name: ListLib Documentation
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: ListLib_Icon.png
  favicon: ListLib_Favicon.png
  font:
    code: Roboto Mono
  palette:
    scheme: slate
    primary: cyan
    accent: cyan
  features:
    - navigation.tabs
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
nav:
  - Home: 
    - "index.md"
    - Quick Start:
      - Installation: "installation.md"
      - DataTypes: "dtypes.md"
      - Importing: "import.md"
    - API:
      - List: "list.md" 
      - NumList: "numlist.md"
    - More Features: "features.md"
  - ChangeLog: 
    - 1.0.x: "1.0.x.md"
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CarbyneUniverse
      name: TheCarbyneUniverse on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/TheCarbyneUniverse
      name: TheCarbyneUniverse on Github
repo_url: https://github.com/TheCarbyneUniverse/ListLib
repo_name: TheCarbyneUniverse/ListLib