site_name: ListLib Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: cyan
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
nav:
  - Home: "index.md"
  - DataTypes: "dtypes.md"
  - Importing: "import.md"
  - API:
    - List: "list.md" 